//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int id_Almacen { get; set; }
        public Nullable<decimal> Altitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<int> Ing { get; set; }
    
        public virtual Ingeniero Ingeniero { get; set; }
    }
}
