//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visita
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Costo { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Altitud { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Tecnologia { get; set; }
        public Nullable<int> Tipo { get; set; }
        [Display(Name ="Pagado")]
        public string EstatusPago { get; set; }
        [Display(Name ="Cobrado")]
        public string EstatusCobro { get; set; }
        public Nullable<System.DateTime> FechaMaxima { get; set; }
        public int Folio { get; set; }
        public Nullable<int> Ingeniero { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Ingeniero Ingeniero1 { get; set; }
        public virtual Tecnologia Tecnologia1 { get; set; }
        public virtual TipoVisita TipoVisita { get; set; }
    }
}
